version: "3.3"

services:
    dea-ws:
        restart: 'always'
        build: ./dea-ws
        container_name: dea-ws
        working_dir: /app
        networks:
            - ws-sql-net
        ports: 
            - 3200:3200
        tty: true
    
    dea-sql:
        image: "mysql:latest"
        restart: 'always'
        container_name: dea-db
        volumes: 
            - ./dea-sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        networks:
            - ws-sql-net
        tty: true

networks:
    ws-sql-net:
        driver: bridge
